const express = require('express');
const router = express.Router();
const Controller = require('../controllers/market.controller');
router.get('/create',Controller.create);
router.post('/',Controller.store);
router.get('/carts',Controller.carts);
router.get('/',Controller.index);
router.get('/:id',Controller.show);
router.delete('/:id', Controller.delate);
module.exports = router;